import = [
  "~/.config/alacritty/themes/themes/iterm.toml"
]

[window]
blur = true
decorations = "Buttonless"
opacity = 0.9

dynamic_padding = true
padding = { x = 16, y = 16}

[font]
size = 12.0
normal.family = "MonaspiceNe Nerd Font Mono"
normal.style = "Regular"

[cursor]
style.shape = "Block"
style.blinking = "On"
