import = [
  "~/.config/alacritty/themes/themes/aura.toml"
]

[window]
blur = true
decorations = "Buttonless"
opacity = 0.95

dynamic_padding = true
padding = { x = 16, y = 16}

[font]
size = 14.0
normal.family = "GeistMono Nerd Font"
normal.style = "Regular"

[cursor]
style.shape = "Block"
style.blinking = "On"
